version: "3.3"
services:
  # Database Service (Mysql)
  mysql-database:
    image: mariadb
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: flask-app
      MYSQL_USER: flask
      MYSQL_PASSWORD: Silencer&&55
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database-data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      flask-app-network:

volumes:
  database-data:

networks:
  flask-app-network: