version: "3.3"
services:
  # Flask
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile

    links:
      # network connection with these services
      - mysql-database
    depends_on:
      - mysql-database
    ports:
      - "5000:5000"

  # Database Service (Mysql)
  mysql-database:
    image: mariadb
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: flask-app
      MYSQL_USER: flask
      MYSQL_PASSWORD: Silencer&&55
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database-data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  database-data: